### ISSUE TITLE
Support VI-mode indication in igloo prompt theme

### ISSUE THREAD

**Issue by lokesh-krishna** [arcticicestudio/igloo#292]
Could you please consider adding an indicator for what VI-mode is active for the prompt theme? 
For example, the [Pure](https://github.com/sindresorhus/pure) theme indicates when you are in command mode by reversing the prompt symbol. You could maybe do something similar? Or add an element?

**Comment by arcticicestudio** [comment]
Hi @lokesh-krishna 👋🏼 , thanks for your proposal 👍🏼 

Even though these _.dotfiles_ are open source, they are mainly focused on my personal setup and needs.
I don't use ZSHs Vim mode and don't plan to do so either, I must reject this proposal 😕

But you can still implement on your own, e.g. by making use of the right-side prompt (`$RPS1`) instead of adding another element to the main prompt which might reduce it's slick and simple style. After a quick research I found some blog posts like [“Adding Vi To Your Zsh“](https://dougblack.io/words/zsh-vi-mode.html) (see section “Color Prompt Function“) that can be helpful to add it to your own setup without the need to touch the source code of the _igloo_ prompt.
